#------------------------------------------------------------------------------
# grasp - algorithmic framework for SAT.
#------------------------------------------------------------------------------

include $(GRASP_PATH)/Make_defs.include

TG	= grasp
TGDIR	= $(SRCDIR)/libs/$(TG)

TGSRC	= grp_SAT.cc grp_Mode.cc grp_Cmds.cc grp_CNF.cc		\
	  grp_CDB.cc grp_BRE.cc grp_BRE_P.cc grp_FRE.cc		\
	  grp_Preproc.cc grp_Decide.cc

TGOBJ	= $(TGSRC:.cc=.o)

THDR	= grp_SAT.hh grp_Mode.hh grp_Cmds.hh grp_CNF.cc		\
	  grp_CDB.hh grp_BRE.hh grp_BRE_P.hh grp_FRE.hh		\
	  grp_Preproc.hh grp_Decide.hh grp_Deduce.hh grp_Diagnose.hh

MISC	= $(TG).doc Makefile

include $(SRCDIR)/Make_templates.include
include $(SRCDIR)/libs/Make_lib.include

#------------------------------------------------------------------------------

#--DO NOT CHANGE ANYTHING AFTER THIS LINE
grp_SAT.o: grp_SAT.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 /home/jpms/research/.tmp/soft/include/time.hh \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/time.h \
 /usr/include/linux/time.h /usr/include/time.h \
 /usr/include/sys/resource.h /usr/include/limits.h \
 /usr/include/posix1_lim.h /usr/include/linux/limits.h \
 /usr/include/posix2_lim.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/limits.h \
 /usr/include/linux/resource.h /usr/include/asm/resource.h grp_SAT.hh \
 grp_Mode.hh /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh grp_BRE.hh \
 grp_BRE_P.hh grp_FRE.hh grp_Preproc.hh grp_Deduce.hh grp_Diagnose.hh \
 grp_Decide.hh
grp_Mode.o: grp_Mode.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_Mode.hh /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh
grp_Cmds.o: grp_Cmds.cc grp_Cmds.hh \
 /home/jpms/research/.tmp/soft/include/cmdArg.hh \
 /home/jpms/research/.tmp/soft/include/cmdLine.hh \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_Mode.hh
grp_CNF.o: grp_CNF.cc grp_CNF.hh /usr/lib/g++-include/iostream.h \
 /usr/lib/g++-include/streambuf.h /usr/include/libio.h \
 /usr/include/_G_config.h \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h \
 /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h
grp_CDB.o: grp_CDB.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_CDB.hh /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh grp_Mode.hh \
 /home/jpms/research/.tmp/soft/include/array.hh
grp_BRE.o: grp_BRE.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_BRE.hh grp_Mode.hh /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh
grp_BRE_P.o: grp_BRE_P.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_BRE_P.hh grp_BRE.hh grp_Mode.hh \
 /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh
grp_FRE.o: grp_FRE.cc /usr/include/stdio.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_FRE.hh grp_Mode.hh /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh
grp_Preproc.o: grp_Preproc.cc /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_Preproc.hh grp_Mode.hh \
 /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh grp_CNF.hh grp_BRE.hh \
 grp_FRE.hh
grp_Decide.o: grp_Decide.cc /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/lib/g++-include/iostream.h /usr/lib/g++-include/streambuf.h \
 grp_Decide.hh /home/jpms/research/.tmp/soft/include/list.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh grp_Mode.hh \
 /home/jpms/research/.tmp/soft/include/array.hh grp_CDB.hh grp_CNF.hh
