#------------------------------------------------------------------------------
# cnf_parse - Parser for CNF format.
#------------------------------------------------------------------------------

include $(GRASP_PATH)/Make_defs.include

TG	= cnf_parse
TGDIR	= $(SRCDIR)/libs/parse/$(TG)

TGSRC	= cnf_Parser.cc

TGOBJ	= $(TGSRC:.cc=.o)

THDR	= cnf_Parser.hh

MISC	= $(TG).doc Makefile

include $(SRCDIR)/Make_templates.include
include $(SRCDIR)/libs/Make_lib.include

#------------------------------------------------------------------------------

#--DO NOT CHANGE ANYTHING AFTER THIS LINE
cnf_Parser.o: cnf_Parser.cc /usr/include/stdio.h \
 /usr/include/features.h /usr/include/sys/cdefs.h /usr/include/libio.h \
 /usr/include/_G_config.h /usr/include/stdlib.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h /usr/include/string.h \
 /usr/lib/g++-include/fstream.h /usr/lib/g++-include/iostream.h \
 /usr/lib/g++-include/streambuf.h cnf_Parser.hh \
 /home/jpms/research/.tmp/soft/include/defs.hh \
 /home/jpms/research/.tmp/soft/include/macros.hh \
 /home/jpms/research/.tmp/soft/include/array.hh \
 /home/jpms/research/.tmp/soft/include/grp_SAT.hh \
 /home/jpms/research/.tmp/soft/include/time.hh \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/time.h \
 /usr/include/linux/time.h /usr/include/time.h \
 /usr/include/sys/resource.h /usr/include/limits.h \
 /usr/include/posix1_lim.h /usr/include/linux/limits.h \
 /usr/include/posix2_lim.h \
 /usr/lib/gcc-lib/i586-unknown-linux/2.7.2.1/include/limits.h \
 /usr/include/linux/resource.h /usr/include/asm/resource.h \
 /home/jpms/research/.tmp/soft/include/grp_Mode.hh \
 /home/jpms/research/.tmp/soft/include/grp_CDB.hh \
 /home/jpms/research/.tmp/soft/include/memory.hh \
 /home/jpms/research/.tmp/soft/include/list.hh \
 /home/jpms/research/.tmp/soft/include/grp_CNF.hh \
 /home/jpms/research/.tmp/soft/include/grp_BRE.hh \
 /home/jpms/research/.tmp/soft/include/grp_BRE_P.hh \
 /home/jpms/research/.tmp/soft/include/grp_FRE.hh \
 /home/jpms/research/.tmp/soft/include/grp_Preproc.hh \
 /home/jpms/research/.tmp/soft/include/grp_Deduce.hh \
 /home/jpms/research/.tmp/soft/include/grp_Diagnose.hh \
 /home/jpms/research/.tmp/soft/include/grp_Decide.hh
